services:
  backend:
    build: ./backend
    container_name: smartcampus-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads_volume:/uploads
    networks:
      - smartcampus-network

  frontend:
    build: ./frontend
    container_name: smartcampus-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - smartcampus-network

networks:
  smartcampus-network:
    driver: bridge

volumes:
  uploads_volume:
    driver: local